"""
Pydantic models for request/response validation and data structures.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class ConversationState(str, Enum):
    """Lifecycle states for a conversation session."""
    PENDING = "PENDING"
    SCAM_DETECTED = "SCAM_DETECTED"
    ENGAGING = "ENGAGING"
    COMPLETED = "COMPLETED"
    CALLBACK_SENT = "CALLBACK_SENT"


class Metadata(BaseModel):
    """Metadata for incoming webhook requests."""
    source: Optional[str] = Field(None, description="Source platform/channel")
    timestamp: Optional[str] = Field(None, description="Original message timestamp")
    userAgent: Optional[str] = Field(None, description="User agent if available")
    ipAddress: Optional[str] = Field(None, description="IP address if available")
    additionalData: Optional[Dict[str, Any]] = Field(None, description="Any additional metadata")


class MessageObject(BaseModel):
    """Structure for a single message in the conversation."""
    sender: str = Field(..., description="Sender role: 'scammer' or 'user'")
    text: str = Field(..., description="Message content")
    timestamp: int = Field(..., description="Epoch timestamp in ms")


class WebhookRequest(BaseModel):
    """Input schema for POST /webhook endpoint."""
    sessionId: str = Field(..., description="Unique session identifier")
    message: MessageObject = Field(..., description="Incoming message object")
    conversationHistory: List[MessageObject] = Field(
        default_factory=list,
        description="Previous messages in this conversation"
    )
    metadata: Optional[Metadata] = Field(None, description="Additional metadata")


class ExtractedIntelligence(BaseModel):
    """Structured intelligence extracted from conversation."""
    bankAccounts: List[str] = Field(default_factory=list)
    upiIds: List[str] = Field(default_factory=list)
    phishingLinks: List[str] = Field(default_factory=list)
    phoneNumbers: List[str] = Field(default_factory=list)
    suspiciousKeywords: List[str] = Field(default_factory=list)


class AgentNotes(BaseModel):
    """Notes generated by the AI agent about the scam attempt."""
    scam_type: str = Field(default="unknown", description="Type of scam identified")
    tactics_used: List[str] = Field(default_factory=list, description="Pressure tactics observed")
    extracted_entities: List[str] = Field(default_factory=list, description="Names/organizations mentioned")
    risk_assessment: str = Field(default="medium", description="Risk level: high/medium/low")
    summary: str = Field(default="", description="Brief summary of interaction")


class WebhookResponse(BaseModel):
    """Output schema for POST /webhook endpoint."""
    status: str = Field(..., description="Response status: success/error")
    reply: str = Field(..., description="Agent reply or empty if completed")


class CallbackPayload(BaseModel):
    """Payload schema for final callback to platform."""
    sessionId: str = Field(..., description="Session identifier")
    scamDetected: bool = Field(..., description="Whether scam was detected")
    totalMessagesExchanged: int = Field(..., description="Total messages in conversation")
    extractedIntelligence: ExtractedIntelligence = Field(..., description="Extracted intelligence data")
    agentNotes: str = Field(..., description="Agent-generated notes about the scam")


class ConversationSession(BaseModel):
    """Internal model for tracking conversation state."""
    session_id: str
    state: ConversationState = ConversationState.PENDING
    messages: List[Dict[str, Any]] = Field(default_factory=list)
    total_messages_exchanged: int = 0
    scam_detected: bool = False
    extracted_intelligence: ExtractedIntelligence = Field(default_factory=ExtractedIntelligence)
    agent_notes: Optional[AgentNotes] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    last_message_at: Optional[datetime] = None
    turn_count: int = 0
    intelligence_count: int = 0

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class ScamDetectionResult(BaseModel):
    """Result of scam detection analysis."""
    is_scam: bool
    confidence_score: float
    matched_keywords: List[str]
    urgency_score: int
    payment_redirection_detected: bool
    reasons: List[str]


class HealthResponse(BaseModel):
    """Health check response."""
    status: str
    version: str
    timestamp: str
